# coding: utf-8
# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
"""Memory abstraction strategy implementations.

All strategies implement the same interface:

    strategy.inject(memory_text: str, query: str, char_limit: int) -> str

where:
  memory_text  — full MEMORY.md content
  query        — the current user message (used for retrieval)
  char_limit   — maximum characters to inject

The returned string is the memory context block injected into the system prompt.
"""
from __future__ import annotations

import math
import re
from abc import ABC, abstractmethod
from typing import List, Optional, Tuple


# ── Base ──────────────────────────────────────────────────────────────────────


class MemoryStrategy(ABC):
    """Abstract memory injection strategy."""

    name: str = "base"

    @abstractmethod
    async def inject(
        self,
        memory_text: str,
        query: str,
        char_limit: int,
    ) -> Tuple[str, int]:
        """Return (injected_text, chars_used)."""
        ...


# ── Strategy A — Inject-all (current production behaviour) ───────────────────


class InjectAllStrategy(MemoryStrategy):
    """Inject the full MEMORY.md, truncated to char_limit."""

    name = "inject_all"

    async def inject(self, memory_text: str, query: str, char_limit: int) -> Tuple[str, int]:
        truncated = memory_text[:char_limit]
        return truncated, len(truncated)


# ── Strategy B — Top-K semantic retrieval ─────────────────────────────────────


class TopKRetrievalStrategy(MemoryStrategy):
    """Embed each memory entry; inject top-K most similar to the current query."""

    name = "top_k_retrieval"

    def __init__(
        self,
        embedding_model: str = "openai/text-embedding-3-small",
        k: int = 5,
        dry_run: bool = False,
    ) -> None:
        self._embedding_model = embedding_model
        self._k = k
        self._dry_run = dry_run

    async def inject(self, memory_text: str, query: str, char_limit: int) -> Tuple[str, int]:
        entries = _split_memory_entries(memory_text)
        if not entries or self._dry_run:
            # Fall back to inject-all in dry-run
            top = entries[: self._k]
            injected = "\n\n".join(top)[:char_limit]
            return injected, len(injected)

        query_vec = await _embed(query, self._embedding_model)
        scored: List[Tuple[float, str]] = []
        for entry in entries:
            entry_vec = await _embed(entry, self._embedding_model)
            sim = _cosine(query_vec, entry_vec)
            scored.append((sim, entry))

        scored.sort(reverse=True)
        top = [entry for _, entry in scored[: self._k]]
        injected = "\n\n".join(top)[:char_limit]
        return injected, len(injected)


# ── Strategy C — Hierarchical consolidation ───────────────────────────────────


class HierarchicalStrategy(MemoryStrategy):
    """Maintain episodic (raw) and semantic (consolidated) memory layers.

    Semantic summaries are generated by a small LLM.  New entries are
    episodic; entries older than `consolidation_window_entries` are
    summarised into semantic memory.
    """

    name = "hierarchical"

    def __init__(
        self,
        model: str = "openai/gpt-4.1-nano",
        consolidation_window: int = 10,
        dry_run: bool = False,
    ) -> None:
        self._model = model
        self._window = consolidation_window
        self._dry_run = dry_run
        self._semantic_summary: Optional[str] = None

    async def inject(self, memory_text: str, query: str, char_limit: int) -> Tuple[str, int]:
        entries = _split_memory_entries(memory_text)

        # Recent entries = episodic
        episodic = entries[-self._window:] if len(entries) > self._window else entries
        older = entries[: max(0, len(entries) - self._window)]

        # Consolidate older entries into semantic summary
        if older and not self._dry_run:
            self._semantic_summary = await _consolidate(older, self._model)
        elif older:
            self._semantic_summary = f"[Summary of {len(older)} older entries]"

        parts: List[str] = []
        if self._semantic_summary:
            parts.append(f"## Memory Summary\n{self._semantic_summary}")
        if episodic:
            parts.append("## Recent Observations\n" + "\n\n".join(episodic))

        injected = "\n\n".join(parts)[:char_limit]
        return injected, len(injected)


# ── Strategy D — Recency-weighted hybrid ─────────────────────────────────────


class RecencyHybridStrategy(MemoryStrategy):
    """Inject recent entries verbatim + extractive summary of older entries.

    Recent = entries from last `recent_entry_count` items.
    Older entries are summarised by selecting the most unique sentences.
    """

    name = "recency_hybrid"

    def __init__(self, recent_entry_count: int = 5) -> None:
        self._recent = recent_entry_count

    async def inject(self, memory_text: str, query: str, char_limit: int) -> Tuple[str, int]:
        entries = _split_memory_entries(memory_text)
        recent = entries[-self._recent:] if len(entries) > self._recent else entries
        older = entries[: max(0, len(entries) - self._recent)]

        parts: List[str] = []
        if older:
            summary = _extractive_summary(older, max_sentences=5)
            parts.append(f"## Condensed history\n{summary}")
        if recent:
            parts.append("## Recent\n" + "\n\n".join(recent))

        injected = "\n\n".join(parts)[:char_limit]
        return injected, len(injected)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _split_memory_entries(memory_text: str) -> List[str]:
    """Split MEMORY.md into individual entries separated by blank lines or bullet markers."""
    # Split on double-newline blocks, filter empties
    blocks = re.split(r"\n{2,}", memory_text.strip())
    return [b.strip() for b in blocks if b.strip()]


async def _embed(text: str, model: str) -> List[float]:
    import litellm
    response = await litellm.aembedding(model=model, input=[text[:4000]])
    return response.data[0]["embedding"]


def _cosine(a: List[float], b: List[float]) -> float:
    dot = sum(x * y for x, y in zip(a, b))
    ma = math.sqrt(sum(x * x for x in a))
    mb = math.sqrt(sum(y * y for y in b))
    if ma == 0 or mb == 0:
        return 0.0
    return dot / (ma * mb)


async def _consolidate(entries: List[str], model: str) -> str:
    """Ask a small LLM to consolidate a list of memory entries into a summary."""
    import litellm
    content = "\n\n".join(entries[:20])  # cap to avoid large prompts
    response = await litellm.acompletion(
        model=model,
        messages=[{
            "role": "user",
            "content": (
                f"Summarise these agent memory entries into 3-5 concise bullet points. "
                f"Keep only facts, discard redundancy.\n\n{content}"
            ),
        }],
        max_tokens=200,
        temperature=0.0,
    )
    return response.choices[0].message.content.strip()


def _extractive_summary(entries: List[str], max_sentences: int = 5) -> str:
    """Simple extractive summary: pick the longest/most informative sentences."""
    sentences: List[str] = []
    for entry in entries:
        for sent in re.split(r"(?<=[.!?])\s+", entry):
            sent = sent.strip()
            if len(sent) > 20:
                sentences.append(sent)

    # Rank by length (longer sentences tend to carry more information)
    sentences.sort(key=len, reverse=True)
    return " ".join(sentences[:max_sentences])


ALL_STRATEGIES = [
    InjectAllStrategy(),
    TopKRetrievalStrategy(k=3),
    TopKRetrievalStrategy(k=5),
    TopKRetrievalStrategy(k=10),
    HierarchicalStrategy(),
    RecencyHybridStrategy(),
]
